apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240226112422.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240226112422.0.0+build.6aff574
  releaseNotes: |
    Release v20240226112422.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-26-02-2024-04-34-37-995375305/where-for-dinner-my-apps-bundle@sha256:262b6bf25d3a569f03f246b5a196a95e0379dec92daff3958ba6f9ab1d90fadb
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

