apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240226113242.0.0+build.6aff574
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240226113242.0.0+build.6aff574
  releaseNotes: |
    Release v20240226113242.0.0+build.6aff574 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-26-02-2024-04-34-37-995375305/where-for-dinner-search-proc-my-apps-bundle@sha256:8b929f5392fa8cd963cedb1822e0b954655f724de697c3df962952f58fe86151
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

